// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsEKA6PejoUOalnZXRqsShy2jzhmdiBQ',
    appId: '1:341754234293:web:b5ad4467c13b019d6e45fc',
    messagingSenderId: '341754234293',
    projectId: 'cart-pal-70998614-206fe',
    authDomain: 'cart-pal-70998614-206fe.firebaseapp.com',
    storageBucket: 'cart-pal-70998614-206fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuDKuIa15aoTSOu44tw2YKLE1HkVIL74c',
    appId: '1:341754234293:android:48a201dad5aae6706e45fc',
    messagingSenderId: '341754234293',
    projectId: 'cart-pal-70998614-206fe',
    storageBucket: 'cart-pal-70998614-206fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoa9rHqZiUUtxr-4mc-W2yI-hEPKzUsxM',
    appId: '1:341754234293:ios:765ca7e563041dcb6e45fc',
    messagingSenderId: '341754234293',
    projectId: 'cart-pal-70998614-206fe',
    storageBucket: 'cart-pal-70998614-206fe.firebasestorage.app',
    iosBundleId: 'com.example.cartPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoa9rHqZiUUtxr-4mc-W2yI-hEPKzUsxM',
    appId: '1:341754234293:ios:765ca7e563041dcb6e45fc',
    messagingSenderId: '341754234293',
    projectId: 'cart-pal-70998614-206fe',
    storageBucket: 'cart-pal-70998614-206fe.firebasestorage.app',
    iosBundleId: 'com.example.cartPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdsEKA6PejoUOalnZXRqsShy2jzhmdiBQ',
    appId: '1:341754234293:web:5725fca78f62cf766e45fc',
    messagingSenderId: '341754234293',
    projectId: 'cart-pal-70998614-206fe',
    authDomain: 'cart-pal-70998614-206fe.firebaseapp.com',
    storageBucket: 'cart-pal-70998614-206fe.firebasestorage.app',
  );
}
